[libraries]
IndexedTensor  = { desc = "Indexed tensor and contraction"}
SimpleTensorNetworks   = { desc = "Simple tensor trains/tree tensor networks" }
MPI = { desc = "MPI" }
QuanticsTransforms   = { desc = "Quantics transforms" }
TensorNetworks   = { desc = "ITensor-based tensor networks" }
TensorNetworkContractions = { desc = "Contractions algorithms" }
TCICore = { desc = "TCI core algorithms (LU decomposition, etc.)" }
TensorCrossInterpolation = { desc = "TCI for TT" }
ParallelTCI = { desc = "Parallelized TCI" }
ParallelMPOContractions = { desc = "Parallelized MPO contractions" }
TreeTCI = { desc = "TCI for tree tensors" }
QuanticsGrids = { desc = "Quantics grids" }
QuanticsTCI = { desc = "Sugar coating for TCI + QTT" }
TensorNetworkOperations = { desc = "Quantics.jl - QuanticsTransofms.jl" }
ProjMPSs = { desc = "Adaptive patching + multiplication" }
PatchedTCI = { desc = "Adaptive patching + TCI" }

[library_dependencies.IndexedTensor]
strong_deps = []
weak_deps   = []
test_deps   = []

[library_dependencies.TensorNetworks]
strong_deps = ["IndexedTensor"]
weak_deps   = []
test_deps   = []

[library_dependencies.SimpleTensorNetworks]
strong_deps = []
weak_deps   = []
test_deps   = []

[library_dependencies.QuanticsTransforms]
strong_deps = ["SimpleTensorNetworks", "QuanticsGrids"]
weak_deps   = ["TensorNetworks"]
test_deps   = []

[library_dependencies.TCICore]
strong_deps = []
weak_deps   = []
test_deps   = []

[library_dependencies.TensorCrossInterpolation]
strong_deps = ["SimpleTensorNetworks", "TCICore"]
weak_deps   = ["IndexedTensor", "TensorNetworks"]
test_deps   = []

[library_dependencies.ParallelTCI]
strong_deps = ["TCICore", "SimpleTensorNetworks", "MPI"]
weak_deps   = []
test_deps   = []

[library_dependencies.ParallelMPOContractions]
strong_deps = ["MPI"]
weak_deps   = ["TensorNetworks"]
test_deps   = []

[library_dependencies.TreeTCI]
strong_deps = ["TCICore", "SimpleTensorNetworks"]
weak_deps   = []
test_deps   = []

[library_dependencies.QuanticsGrids]
strong_deps = []
weak_deps   = []
test_deps   = []

[library_dependencies.QuanticsTCI]
strong_deps   = ["TensorCrossInterpolation", "QuanticsGrids"]
weak_deps   = []
test_deps   = []

[library_dependencies.TensorNetworkContractions]
strong_deps   = ["IndexedTensor", "TensorNetworks"]
weak_deps   = []
test_deps   = []

[library_dependencies.TensorNetworkOperations]
strong_deps   = ["TensorNetworkContractions", "TensorNetworks"]
weak_deps   = []
test_deps   = []

[library_dependencies.ProjMPSs]
strong_deps   = ["IndexedTensor", "TensorNetworks"]
weak_deps   = []
test_deps   = []

[library_dependencies.PatchedTCI]
strong_deps   = ["IndexedTensor", "TensorNetworks", "TensorCrossInterpolation", "TensorNetworkOperations"]
weak_deps   = []
test_deps   = []